apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      run: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        run: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: rolandawoda/reverseproxy:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m
       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    service: reverseproxy
